jogadores/urls.py
from django.urls import path
from jogadores import views

app_name='jogadores'
urlpatterns = [
    path(r'listar/', views.listar_jogadores, name='listar_jogadores'),
    path(r'detalhar/<slug:username>/', views.detalhar_jogador, name='detalhar_jogador'),
    path(r'editar/<slug:username>/', views.editar_jogador, name='editar_jogador'),
]

ladder/urls.py
from django.urls import path

from ladder import views

app_name='ladder'
urlpatterns = [
    # Ladder
    path(r'atual/', views.detalhar_ladder_atual, name='detalhar_ladder_atual'),
    path(r'hall-fama/<int:ano>/<int:indice>/', views.detalhar_hall_fama, name='detalhar_hall_fama'),
    path(r'historico/<int:ano>/<int:mes>/', views.detalhar_ladder_historico, name='detalhar_ladder_historico'),
    path(r'hall-fama/listar/', views.listar_hall_fama, name='listar_hall_fama'),
    path(r'historico/listar/', views.listar_ladder_historico, name='listar_ladder_historico'),
    path(r'atual/listar-desafios/', views.listar_desafios_ladder, name='listar_desafios_ladder_atual'),
    path(r'historico/<int:ano>/<int:mes>/listar-desafios/', views.listar_desafios_ladder, name='listar_desafios_ladder_historico'),
    path(r'hall-fama/<int:ano>/<int:indice>/listar-desafios/', views.listar_desafios_season, name='listar_desafios_season'),
    
    # Remoções
    path(r'cancelar-remocao/<int:remocao_id>/', views.cancelar_remocao_jogador_ladder, name='cancelar_remocao_jogador_ladder'),
    path(r'listar-remocoes/', views.listar_remocoes_jogador_ladder, name='listar_remocoes_jogador_ladder'),
    path(r'remover-jogador/', views.remover_jogador_ladder, name='remover_jogador_ladder'),
    
    # Permissões de aumento de range
    path(r'permissao-aumento-range/adicionar/', views.add_permissao_aumento_range, name='add_permissao_aumento_range'),
    path(r'permissao-aumento-range/remover/', views.remover_permissao_aumento_range, name='remover_permissao_aumento_range'),
    path(r'permissao-aumento-range/remover/<int:permissao_id>/', views.remover_permissao_aumento_range, name='remover_permissao_aumento_range'),
    
    # Desafios de ladder
    path(r'desafio/adicionar/', views.add_desafio_ladder, name='adicionar_desafio_ladder'),
    path(r'desafio/cancelar/<int:desafio_id>/', views.cancelar_desafio_ladder, name='cancelar_desafio_ladder'),
    path(r'desafio/detalhar/<int:desafio_id>/', views.detalhar_desafio_ladder, name='detalhar_desafio_ladder'),
    path(r'desafio/editar/<int:desafio_id>/', views.editar_desafio_ladder, name='editar_desafio_ladder'),
    path(r'desafio/listar-pendentes/', views.listar_desafios_ladder_pendentes_validacao, name='listar_desafios_ladder_pendentes_validacao'),
    path(r'desafio/validar/<int:desafio_id>/', views.validar_desafio_ladder, name='validar_desafio_ladder'),
    
    # Regras
    path(r'regras/', views.detalhar_regras, name='detalhar_regras_ladder'),
    
    # Lutas
    path(r'lutas/detalhar/<int:luta_id>/', views.detalhar_luta, name='detalhar_luta'),
    
    # Análises
    path('analises/geral/', views.analises, name='analises'),
    path('analises/geral/resultado-acumulado-jogadores/', views.analise_resultado_acumulado_jogadores, name='analise_result_acum_jogadores'),
    path('analises/geral/resultado-posicao/', views.analise_resultado_por_posicao, name='analise_resultado_por_posicao'),
    path('analises/geral/resultado-diferenca-posicao/', views.analise_resultado_por_diferenca_posicao, name='analise_resultado_por_diferenca_posicao'),
    path('analises/geral/vitorias-por-personagem/', views.analise_vitorias_por_personagem, name='analise_vitorias_por_personagem'),
    path('analises/jogador/', views.analises_por_jogador, name='analises_por_jogador'),
    path('analises/jogador/resultado-acumulado-jogador/', views.analise_resultado_acumulado_para_um_jogador, name='analise_result_acum_jogador'),
    path('analises/jogador/resultado-contra-personagens-jogador/', views.analise_resultado_acumulado_contra_personagens_para_um_jogador, 
         name='analise_result_jogador_contra_personagens'),
    path('analises/jogador/resultado-stages-jogador/', views.analise_resultado_stages_para_um_jogador, name='analise_stages_jogador'),
    path('analises/jogador/vitorias-desafio/', views.analise_vitorias_desafio_para_um_jogador, name='analise_vitorias_desafio_jogador'),
]

smashLadder/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls.conf import re_path
from django.views.defaults import page_not_found

from ladder.models import Lockdown
from smashLadder import views, settings


urlpatterns = []

# Verificar lockdown de seasons
try:
    if Lockdown.sistema_em_lockdown():
        urlpatterns.append(re_path(r'.*?', page_not_found, {'exception': Exception('Gerando nova Season')}))
except:
    pass
        
urlpatterns.extend([
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', views.home, name='inicio'),
    
    path('jogadores/', include('jogadores.urls.urls_jogadores')),
    path('ladder/', include('ladder.urls')),
    path('personagens/', include('jogadores.urls.urls_personagens')),
    path('stages/', include('jogadores.urls.urls_stages')),
    path('torneios/', include('torneios.urls')),
    path('treinamento/', include('treinamento.urls')),
])

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

torneios/urls.py
"""
Configuração de URL para torneios
"""
from django.urls import path
from torneios import views

app_name='torneios'
urlpatterns = [
    # Torneios
    path(r'criar/', views.criar_torneio, name='criar_torneio'),
    path(r'detalhar/<int:torneio_id>/', views.detalhar_torneio, name='detalhar_torneio'),
    path(r'editar/<int:torneio_id>/', views.editar_torneio, name='editar_torneio'),
    path(r'listar/', views.listar_torneios, name='listar_torneios'),
    
    # Partidas
    path(r'detalhar/<int:torneio_id>/partida/<int:partida_id>/', views.detalhar_partida, name='detalhar_partida'),
    path(r'detalhar/<int:torneio_id>/partidas/', views.listar_partidas, name='listar_partidas'),
    
    # Jogadores
    path(r'detalhar/<int:torneio_id>/jogador/<int:jogador_id>/', views.detalhar_jogador, name='detalhar_jogador_torneio'),
    path(r'editar/<int:torneio_id>/jogador/<int:jogador_id>/', views.editar_jogador, name='editar_jogador_torneio'),
    path(r'detalhar/<int:torneio_id>/jogadores/', views.listar_jogadores, name='listar_jogadores_torneio'),
    
    # Análises
    path('analises/jogador/', views.analises_por_jogador, name='analises_torneio_por_jogador'),
    path('analises/jogador/resultado/', views.analise_resultado_torneio_para_um_jogador, name='analise_torneio_resultado_por_jogador'),
    path('analises/time/', views.analises_por_time, name='analises_torneio_por_time'),
    path('analises/time/resultado/', views.analise_resultado_torneio_para_um_time, name='analise_torneio_resultado_por_time'),
    
]

jogadores/views.py
# -*- coding: utf-8 -*-
"""Views para jogadores"""

import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db import transaction
from django.db.models.aggregates import Count, Max, Sum
from django.db.models.expressions import F, Value
from django.db.models.fields import IntegerField
from django.db.models.query import prefetch_related_objects
from django.db.models.query_utils import Q
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls.base import reverse
from django.utils import timezone

from jogadores.forms import JogadorForm, StagesValidasForm, FeedbackForm, \
    SugestaoLadderForm
from jogadores.models import Jogador, Stage, StageValidaLadder, Personagem, \
    Feedback, SugestaoLadder
from ladder.models import DesafioLadder, Luta, ResultadoDesafioLadder, \
    JogadorLuta, RemocaoJogador, ResultadoDecaimentoJogador, Season
from ladder.utils import buscar_desafiaveis
from torneios.models import JogadorTorneio


def detalhar_jogador(request, username):
    """Detalhar um jogador específico pelo nick"""
    jogador = get_object_or_404(Jogador.objects.select_related('main'), user__username=username)
    
    # Detalhar resultados de desafios do jogador
    desafios = {}
    desafios_feitos = list(DesafioLadder.validados.filter(desafiante=jogador).select_related('desafiante', 'desafiado'))
    desafios_recebidos = list(DesafioLadder.validados.filter(desafiado=jogador).select_related('desafiante', 'desafiado'))
    
    desafios['feitos'] = len(desafios_feitos)
    desafios['recebidos'] = len(desafios_recebidos)
    desafios['vitorias'] = len([vitoria for vitoria in desafios_feitos if vitoria.score_desafiante > vitoria.score_desafiado]) \
        + len([vitoria for vitoria in desafios_recebidos if vitoria.score_desafiante < vitoria.score_desafiado])
    desafios['derrotas'] = len([derrota for derrota in desafios_feitos if derrota.score_desafiante < derrota.score_desafiado]) \
        + len([derrota for derrota in desafios_recebidos if derrota.score_desafiante > derrota.score_desafiado]) \
    
    jogador.percentual_vitorias = desafios['vitorias'] * 100 / ((desafios['vitorias'] + desafios['derrotas']) or 1)
    
    # Posição atual na ladder
    jogador.posicao_atual = jogador.posicao_em(timezone.localtime())
    
    # Buscar primeiro desafio
    todos_desafios = desafios_feitos
    todos_desafios.extend(desafios_recebidos)
    # Ordenar por data
    todos_desafios.sort(key = lambda x: x.data_hora)
    
    # Preencher gráfico com percentual de vitórias
    jogador.grafico_percentual_vitorias = list()
    qtd_vitorias = 0
    qtd_desafios = 0
    
    for desafio in todos_desafios:
        if desafio.desafiante_id == jogador.id and desafio.score_desafiante > desafio.score_desafiado:
            qtd_vitorias += 1
        elif desafio.desafiado_id == jogador.id and desafio.score_desafiante < desafio.score_desafiado:
            qtd_vitorias += 1
        qtd_desafios += 1
        percentual_vitorias = qtd_vitorias * 100 / qtd_desafios 
        jogador.grafico_percentual_vitorias.append(round(percentual_vitorias, 2))
        
    # Preencher gráfico de variação de posição utilizando resultados
    jogador.grafico_variacao_posicao = list()
    
    # Verificar se jogador possui desafios
    if todos_desafios:
        # Buscar season atual
        season_atual = Season.objects.all().order_by('-data_inicio')[0]
        
        # Verificar se jogador possui remoções
        if RemocaoJogador.objects.filter(jogador=jogador, data__gte=season_atual.data_hora_inicio).exists():
            # Buscar última remoção
            ultima_remocao = RemocaoJogador.objects.filter(jogador=jogador, data__gte=season_atual.data_hora_inicio).order_by('-data')[0]
            
            for desafio in todos_desafios:
                if desafio.data_hora > ultima_remocao.data:
                    primeiro_desafio = desafio
                    break
            else:
                primeiro_desafio = None
        else:
            for desafio in todos_desafios:
                if desafio.data_hora.date() >= season_atual.data_inicio:
                    primeiro_desafio = desafio
                    break
            else:
                primeiro_desafio = None
        
        # Se possui um desafio válido na season atual, montar gráfico de variação
        if primeiro_desafio:
            data_inicial = primeiro_desafio.data_hora
        
            if primeiro_desafio.desafiante_id == jogador.id:
                posicao_inicial = primeiro_desafio.posicao_desafiante
            else:
                posicao_inicial = primeiro_desafio.posicao_desafiado
        
            jogador.grafico_variacao_posicao.append({'x': data_inicial.strftime('%d/%m/%Y %H:%M'), 'y': posicao_inicial})
        
            # Preencher gráfico com variações a partir dessa data
            posicao_atual = posicao_inicial
            resultados_desafios = list(ResultadoDesafioLadder.objects.filter(jogador=jogador, desafio_ladder__data_hora__gte=data_inicial) \
                                       .annotate(data_hora=F('desafio_ladder__data_hora')) \
                                       .values('data_hora').annotate(alteracao_total=Sum('alteracao_posicao')) \
                                       .annotate(tipo=Value(1, output_field=IntegerField())) \
                                       .values('alteracao_total', 'data_hora', 'tipo').order_by('data_hora', 'desafio_ladder__posicao_desafiado'))
            resultados_decaimentos = list(ResultadoDecaimentoJogador.objects.filter(jogador=jogador, decaimento__data__gte=data_inicial) \
                                          .annotate(data_hora=F('decaimento__data')) \
                                          .values('data_hora').annotate(alteracao_total=Sum('alteracao_posicao')) \
                                          .annotate(tipo=Value(2, output_field=IntegerField())) \
                                          .values('alteracao_total', 'data_hora', 'tipo').order_by('data_hora', 'decaimento__posicao_inicial'))
            resultados_remocoes = list(RemocaoJogador.objects.filter(data__gte=data_inicial).annotate(data_hora=F('data'))
                                       .annotate(tipo=Value(3, output_field=IntegerField())) \
                                       .values('posicao_jogador', 'data_hora', 'tipo').order_by('data_hora', 'posicao_jogador'))
            
            resultados = resultados_desafios
            resultados.extend(resultados_decaimentos)
            resultados.extend(resultados_remocoes)
            
            resultados.sort(key=lambda x: x['data_hora'])
            
            for indice, resultado in enumerate(resultados):
                if resultado['tipo'] in [1, 2]:
                    posicao_atual += resultado['alteracao_total']
                elif resultado['tipo'] == 3:
                    if resultado['posicao_jogador'] < posicao_atual:
                        posicao_atual -= 1
                        
                if indice == len(resultados)-1 or (resultado['data_hora'] != resultados[indice+1]['data_hora']):
                    jogador.grafico_variacao_posicao.append({'x': resultado['data_hora'].strftime('%d/%m/%Y %H:%M'), 'y': posicao_atual})
                        
        # Adicionar últimos desafios
        jogador.ultimos_desafios = list(reversed(todos_desafios[-3:]))
            
#         jogador.qtd_lutas = JogadorLuta.objects.filter(jogador=jogador).count()
        jogador.qtd_lutas = DesafioLadder.validados.filter(Q(desafiante=jogador) | Q(desafiado=jogador)) \
            .aggregate(qtd_lutas=Sum(F('score_desafiante') + F('score_desafiado')))['qtd_lutas']
        
        # Adicionar top 5 personagens mais usados
        jogador.top_5_personagens = JogadorLuta.objects.filter(jogador=jogador, personagem__isnull=False, 
                                                               luta__lutaladder__desafio_ladder__cancelamentodesafioladder__isnull=True, 
                                                               luta__lutaladder__desafio_ladder__admin_validador__isnull=False) \
                                                               .values('personagem') \
            .annotate(qtd_lutas=Count('personagem')).order_by('-qtd_lutas')[:5]

        # Buscar personagens para preencher nome
        personagens_top_5 = Personagem.objects.filter(id__in=[registro['personagem'] for registro in jogador.top_5_personagens])
        for registro in jogador.top_5_personagens:
            for personagem in personagens_top_5:
                if registro['personagem'] == personagem.id:
                    registro['personagem'] = personagem
                    break
                
    # Adicionar torneios participados
    jogador.torneios = JogadorTorneio.objects.filter(jogador=jogador).order_by('-torneio__data').select_related('torneio')
                
    return render(request, 'jogadores/detalhar_jogador.html', {'jogador': jogador, 'desafios': desafios})

def detalhar_stage_id(request, stage_id):
    """Detalha uma stage específica"""
    stage = get_object_or_404(Stage, id=stage_id)
    
    # Definir quantidade de lutas e maior ganhador
    stage.qtd_lutas = Luta.objects.filter(lutaladder__desafio_ladder__cancelamentodesafioladder__isnull=True, 
                                                            lutaladder__desafio_ladder__admin_validador__isnull=False,
                                                            stage=stage).count()
    
    if stage.qtd_lutas > 0:
        # Guarda maior quantidade de vitórias para garantir que apenas um possua essa quantidade
        stage.maior_qtd_vitorias = Luta.objects.filter(lutaladder__desafio_ladder__cancelamentodesafioladder__isnull=True,

templates/jogadores/adicionar_sugestao.html
{% extends 'base.html' %}
{% load static %}

{% block title %}- Adicionar sugestão{% endblock %}

{% block page_header %}
Adicionar sugestão
{% endblock %}

{% block content %}
	<div class="col-12 alert alert-primary mb-0">
		<strong>Escreva aqui alguma melhoria que você gostaria de ver na {{ JOGO }} Ladder {{ UF }}</strong>
	</div>
	<form class="col-12" action="{% url 'jogadores:adicionar_sugestao' %}" method="post">
	    {% csrf_token %}
    	{% include "form_2_colunas.html" with form=form_sugestao %}
    	
	  	<input class="btn btn-lg btn-dark mt-4" type="submit" value="Salvar">
	</form>
{% endblock %}

templates/jogadores/avaliar_jogador.html
{% extends 'base.html' %}
{% load static %}

{% block title %}- Avaliar {{ jogador.nick }}{% endblock %}

{% block page_header %}
Avaliar {{ jogador.nick }}
{% endblock %}

{% block content %}
	<form class="col-12" action="{% url 'jogadores:avaliar_jogador' jogador.user.username %}" method="post">
	    {% csrf_token %}
    	{% include "form.html" with form=form_feedback %}
    	
	  	<input class="btn btn-lg btn-dark mt-4" type="submit" value="Salvar">
	</form>
{% endblock %}

templates/jogadores/detalhar_sugestao.html
{% extends 'base.html' %}


{% block title %}
- Sugestão para a Ladder
{% endblock %}

{% block page_header %}
Sugestão para a Ladder
{% endblock %}

{% block content %}
	<div class="col-12 text-center mb-3">
		<a href="{% url 'jogadores:listar_sugestoes' %}">Voltar para lista de sugestões</a>
	</div>
	
	<div class="card col-12 col-md-3">
	  	<div class="card-body">
	    	<h5 class="card-title">{{ sugestao.jogador.nick }}</h5>
	    	
		    <h6 class="card-subtitle mb-2 text-muted">{{ sugestao.data_hora|date:'d/m/Y H:i' }}</h6>
		    
	    	<p class="card-text">{{ sugestao.texto }}</p>
	  	</div>
	</div>
{% endblock %}

templates/jogadores/editar_jogador.html
{% extends 'base.html' %}
{% load static %}

{% block title %}- Editar {{ jogador.nick }}{% endblock %}

{% block page_header %}
Editar {{ jogador.nick }}
{% endblock %}

{% block extra_header %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block content %}
	<form class="col-12" action="{% url 'jogadores:editar_jogador' jogador.user.username %}" method="post">
	    {% csrf_token %}
    	{% include "form.html" with form=form_jogador %}
    	
	  	<input class="btn btn-lg btn-dark mt-4" type="submit" value="Salvar">
	</form>
{% endblock %}

{% block extra_scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script src={% static "jquery.mask.min.js" %} type="text/javascript"></script>

<script type="text/javascript">
$(document).ready(function(){
	$('select').select2();
	$('.data-hora').mask('00/00/0000 00:00');
});
</script>
{% endblock %}

templates/jogadores/listar_avaliacoes.html
{% extends 'base.html' %}


{% block title %}
- Feedbacks de {{ request.user.jogador.nick }}
{% endblock %}

{% block page_header %}
Feedbacks de {{ request.user.jogador.nick }}
{% endblock %}

{% block content %}
	{% for feedback in feedbacks %}
	<div class="card col-12 col-md-3">
	  	<div class="card-body">
	    	<h5 class="card-title">{{ feedback.avaliador.nick }}</h5>
	    	
		    <h6 class="card-subtitle mb-2 text-muted">{{ feedback.data_hora|date:'d/m/Y H:i' }}</h6>
		    
	    	<p class="card-text">{{ feedback.texto }}</p>
	  	</div>
	</div>
	{% empty %}
	<div class="col-12 text-center">
		<h5>Jogador sem feedbacks cadastrados</h5>
	</div>
	{% endfor %}
{% endblock %}

templates/jogadores/listar_desafiaveis.html
{% extends 'base.html' %}

{% block title %}- Jogadores desafiáveis para {{ jogador.nick }}{% endblock %}

{% block page_header %}
Jogadores desafiáveis para {{ jogador.nick }}
{% endblock %}

{% block content %}	
	<div class="col-12 text-center">
		<p>Data/hora da consulta: <strong>{% now 'd/m/Y H:i:s' %}</strong></p>
	</div>
	
	{% for jogador_desafiavel in desafiaveis %}
	<div class="card col-6 col-md-1">
	  	<div class="card-body text-center">
	  		<p class="card-text"><a href="{% url 'jogadores:detalhar_jogador' jogador_desafiavel.user.username %}">{{ jogador_desafiavel.nick }}</a></p>
	  	</div>
	</div>
	{% empty %}
	<div class="col-12 text-center">
		<h5>Não há jogadores desafiáveis, parabéns!</h5>
	</div>
	{% endfor %}
	
	{% if desafios_pendentes %}
	<div class="col-12 alert alert-danger my-2">
		<strong>Existem desafios pendentes de validação que podem alterar a lista de jogadores desafiáveis!</strong>
	</div>
	
	{% for desafio_ladder in desafios_pendentes %}
	<div class="card col-12 col-md-3">
	  	<div class="card-body">
	  		<div class="row d-flex">
		  		<div class="col-5 text-left d-flex flex-column">
			    	<h5 class="card-title mb-0">{{ desafio_ladder.desafiante.nick }}</h5>
			    	<h6 class="card-title {% if desafio_ladder.score_desafiante > desafio_ladder.score_desafiado %}
		  				text-success
		  			{% else %}
		  				text-danger
		  			{% endif %}">{{desafio_ladder.score_desafiante}}</h6>
		    	</div>
		  		<div class="col-2 text-center">
			    	<h5 class="card-title">VS</h5>
		    	</div>
		  		<div class="col-5 text-right">
			    	<h5 class="card-title mb-0">{{ desafio_ladder.desafiado.nick }}</h5>
			    	<h6 class="card-title
		  			{% if desafio_ladder.score_desafiado > desafio_ladder.score_desafiante %}
		  				text-success
		  			{% else %}
		  				text-danger
		  			{% endif %}">{{desafio_ladder.score_desafiado}}</h6>
		    	</div>
	    	</div>
	    	
		    <h6 class="card-subtitle mb-2 text-muted">{{ desafio_ladder.data_hora|date:'d/m/Y H:i' }}</h6>
		    
		    {% if desafio_ladder.is_cancelado %}
		    	<p class="card-text">Desafio cancelado</p>
		    {% elif desafio_ladder.is_validado %}
		    	<p class="card-text">Desafio validado</p>
		    {% else %}
		    	<p class="card-text">Desafio aguardando validação</p>
		    {% endif %}
		    
		    <a class="card-link" href="{% url 'ladder:detalhar_desafio_ladder' desafio_ladder.id %}">Ver detalhes</a>
	    	{% if request.user.jogador.admin and not desafio_ladder.is_validado %}
		    	<a class="card-link" href="{% url 'ladder:validar_desafio_ladder' desafio_ladder.id %}">Validar</a>
		    {% endif %}
			{% if desafio_ladder.is_cancelavel %}			    
		    	<a class="card-link" href="{% url 'ladder:cancelar_desafio_ladder' desafio_ladder.id %}">Cancelar</a>
	    	{% endif %}
	  	</div>
	</div>
	{% endfor %}
	{% endif %}
{% endblock %}

templates/jogadores/listar_desafios_jogador.html
{% extends 'base.html' %}


{% block title %}
- Desafios de {{ jogador.nick }}
{% endblock %}

{% block page_header %}
Desafios de {{ jogador.nick }}
{% endblock %}

{% block content %}
	<div class="col-12 text-center mb-3">
		<a href="{% url 'jogadores:detalhar_jogador' jogador.user.username %}">Ver dados de {{ jogador.nick }}</a>
	</div>
	
	{% for desafio_ladder in desafios %}
	<div class="card col-12 col-md-3">
	  	<div class="card-body">
	  		<div class="row d-flex">
		  		<div class="col-5 text-left d-flex flex-column">
			    	<h5 class="card-title mb-0">{{ desafio_ladder.desafiante.nick }}</h5>
			    	<h6 class="card-title {% if desafio_ladder.score_desafiante > desafio_ladder.score_desafiado %}
		  				text-success
		  			{% else %}
		  				text-danger
		  			{% endif %}">{{desafio_ladder.score_desafiante}}</h6>
		    	</div>
		  		<div class="col-2 text-center">
			    	<h5 class="card-title">VS</h5>
		    	</div>
		  		<div class="col-5 text-right">
			    	<h5 class="card-title mb-0">{{ desafio_ladder.desafiado.nick }}</h5>
			    	<h6 class="card-title
		  			{% if desafio_ladder.score_desafiado > desafio_ladder.score_desafiante %}
		  				text-success
		  			{% else %}
		  				text-danger
		  			{% endif %}">{{desafio_ladder.score_desafiado}}</h6>
		    	</div>
	    	</div>
	    	
		    <h6 class="card-subtitle mb-2 text-muted">{{ desafio_ladder.data_hora|date:'d/m/Y H:i' }}</h6>
		    
		    {% if desafio_ladder.is_cancelado %}
		    	<p class="card-text">Desafio cancelado</p>
		    {% elif desafio_ladder.is_validado %}
		    	<p class="card-text">Desafio validado</p>
		    {% else %}
		    	<p class="card-text">Desafio aguardando validação</p>
		    {% endif %}
		    
		    <a class="card-link" href="{% url 'ladder:detalhar_desafio_ladder' desafio_ladder.id %}">Ver detalhes</a>
	    	{% if request.user.jogador.admin and not desafio_ladder.is_validado %}
		    	<a class="card-link" href="{% url 'ladder:validar_desafio_ladder' desafio_ladder.id %}">Validar</a>
		    {% endif %}
			{% if desafio_ladder.is_cancelavel %}			    
		    	<a class="card-link" href="{% url 'ladder:cancelar_desafio_ladder' desafio_ladder.id %}">Cancelar</a>
	    	{% endif %}
	  	</div>
	</div>
	{% empty %}
	<div class="col-12 text-center">
		<h5>Jogador sem desafios cadastrados</h5>
	</div>
	{% endfor %}
{% endblock %}

templates/jogadores/listar_jogadores.html
{% extends 'base.html' %}

{% block title %}- Lista de jogadores{% endblock %}

{% block page_header %}
Jogadores
{% endblock %}

{% block content %}	
	{% for jogador in jogadores %}
	<div class="card col-6 col-md-1">
	  	<div class="card-body text-center">
	  		<p class="card-text"><a href="{% url 'jogadores:detalhar_jogador' jogador.user.username %}">{{ jogador.nick }}</a></p>
	  	</div>
	</div>
	{% endfor %}
{% endblock %}

templates/jogadores/listar_sugestoes.html
{% extends 'base.html' %}


{% block title %}
- Sugestões para a Ladder
{% endblock %}

{% block page_header %}
Sugestões para a Ladder
{% endblock %}

{% block content %}
	{% for sugestao in sugestoes %}
	<div class="card col-12 col-md-3">
	  	<div class="card-body">
	    	<h5 class="card-title">{{ sugestao.jogador.nick }}</h5>
	    	
		    <h6 class="card-subtitle mb-2 text-muted">{{ sugestao.data_hora|date:'d/m/Y H:i' }}</h6>
		    
	    	<p class="card-text">{{ sugestao.texto|truncatechars:100 }}</p>
		    <a class="card-link" href="{% url 'jogadores:detalhar_sugestao' sugestao.id %}">Detalhar</a>
	  	</div>
	</div>
	{% empty %}
	<div class="col-12 text-center">
		<h5>Não há sugestões cadastradas</h5>
	</div>
	{% endfor %}
{% endblock %}