jogadores/urls.py
from django.urls import path
from jogadores import views

app_name='jogadores'
urlpatterns = [
    path(r'listar/', views.listar_jogadores, name='listar_jogadores'),
    path(r'detalhar/<slug:username>/', views.detalhar_jogador, name='detalhar_jogador'),
    path(r'editar/<slug:username>/', views.editar_jogador, name='editar_jogador'),
]

ladder/urls.py
from django.urls import path

from ladder import views

app_name='ladder'
urlpatterns = [
    # Ladder
    path(r'atual/', views.detalhar_ladder_atual, name='detalhar_ladder_atual'),
    path(r'hall-fama/<int:ano>/<int:indice>/', views.detalhar_hall_fama, name='detalhar_hall_fama'),
    path(r'historico/<int:ano>/<int:mes>/', views.detalhar_ladder_historico, name='detalhar_ladder_historico'),
    path(r'hall-fama/listar/', views.listar_hall_fama, name='listar_hall_fama'),
    path(r'historico/listar/', views.listar_ladder_historico, name='listar_ladder_historico'),
    path(r'atual/listar-desafios/', views.listar_desafios_ladder, name='listar_desafios_ladder_atual'),
    path(r'historico/<int:ano>/<int:mes>/listar-desafios/', views.listar_desafios_ladder, name='listar_desafios_ladder_historico'),
    path(r'hall-fama/<int:ano>/<int:indice>/listar-desafios/', views.listar_desafios_season, name='listar_desafios_season'),
    
    # Remoções
    path(r'cancelar-remocao/<int:remocao_id>/', views.cancelar_remocao_jogador_ladder, name='cancelar_remocao_jogador_ladder'),
    path(r'listar-remocoes/', views.listar_remocoes_jogador_ladder, name='listar_remocoes_jogador_ladder'),
    path(r'remover-jogador/', views.remover_jogador_ladder, name='remover_jogador_ladder'),
    
    # Permissões de aumento de range
    path(r'permissao-aumento-range/adicionar/', views.add_permissao_aumento_range, name='add_permissao_aumento_range'),
    path(r'permissao-aumento-range/remover/', views.remover_permissao_aumento_range, name='remover_permissao_aumento_range'),
    path(r'permissao-aumento-range/remover/<int:permissao_id>/', views.remover_permissao_aumento_range, name='remover_permissao_aumento_range'),
    
    # Desafios de ladder
    path(r'desafio/adicionar/', views.add_desafio_ladder, name='adicionar_desafio_ladder'),
    path(r'desafio/cancelar/<int:desafio_id>/', views.cancelar_desafio_ladder, name='cancelar_desafio_ladder'),
    path(r'desafio/detalhar/<int:desafio_id>/', views.detalhar_desafio_ladder, name='detalhar_desafio_ladder'),
    path(r'desafio/editar/<int:desafio_id>/', views.editar_desafio_ladder, name='editar_desafio_ladder'),
    path(r'desafio/listar-pendentes/', views.listar_desafios_ladder_pendentes_validacao, name='listar_desafios_ladder_pendentes_validacao'),
    path(r'desafio/validar/<int:desafio_id>/', views.validar_desafio_ladder, name='validar_desafio_ladder'),
    
    # Regras
    path(r'regras/', views.detalhar_regras, name='detalhar_regras_ladder'),
    
    # Lutas
    path(r'lutas/detalhar/<int:luta_id>/', views.detalhar_luta, name='detalhar_luta'),
    
    # Análises
    path('analises/geral/', views.analises, name='analises'),
    path('analises/geral/resultado-acumulado-jogadores/', views.analise_resultado_acumulado_jogadores, name='analise_result_acum_jogadores'),
    path('analises/geral/resultado-posicao/', views.analise_resultado_por_posicao, name='analise_resultado_por_posicao'),
    path('analises/geral/resultado-diferenca-posicao/', views.analise_resultado_por_diferenca_posicao, name='analise_resultado_por_diferenca_posicao'),
    path('analises/geral/vitorias-por-personagem/', views.analise_vitorias_por_personagem, name='analise_vitorias_por_personagem'),
    path('analises/jogador/', views.analises_por_jogador, name='analises_por_jogador'),
    path('analises/jogador/resultado-acumulado-jogador/', views.analise_resultado_acumulado_para_um_jogador, name='analise_result_acum_jogador'),
    path('analises/jogador/resultado-contra-personagens-jogador/', views.analise_resultado_acumulado_contra_personagens_para_um_jogador, 
         name='analise_result_jogador_contra_personagens'),
    path('analises/jogador/resultado-stages-jogador/', views.analise_resultado_stages_para_um_jogador, name='analise_stages_jogador'),
    path('analises/jogador/vitorias-desafio/', views.analise_vitorias_desafio_para_um_jogador, name='analise_vitorias_desafio_jogador'),
]

smashLadder/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls.conf import re_path
from django.views.defaults import page_not_found

from ladder.models import Lockdown
from smashLadder import views, settings


urlpatterns = []

# Verificar lockdown de seasons
try:
    if Lockdown.sistema_em_lockdown():
        urlpatterns.append(re_path(r'.*?', page_not_found, {'exception': Exception('Gerando nova Season')}))
except:
    pass
        
urlpatterns.extend([
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', views.home, name='inicio'),
    
    path('jogadores/', include('jogadores.urls.urls_jogadores')),
    path('ladder/', include('ladder.urls')),
    path('personagens/', include('jogadores.urls.urls_personagens')),
    path('stages/', include('jogadores.urls.urls_stages')),
    path('torneios/', include('torneios.urls')),
    path('treinamento/', include('treinamento.urls')),
])

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

torneios/urls.py
"""
Configuração de URL para torneios
"""
from django.urls import path
from torneios import views

app_name='torneios'
urlpatterns = [
    # Torneios
    path(r'criar/', views.criar_torneio, name='criar_torneio'),
    path(r'detalhar/<int:torneio_id>/', views.detalhar_torneio, name='detalhar_torneio'),
    path(r'editar/<int:torneio_id>/', views.editar_torneio, name='editar_torneio'),
    path(r'listar/', views.listar_torneios, name='listar_torneios'),
    
    # Partidas
    path(r'detalhar/<int:torneio_id>/partida/<int:partida_id>/', views.detalhar_partida, name='detalhar_partida'),
    path(r'detalhar/<int:torneio_id>/partidas/', views.listar_partidas, name='listar_partidas'),
    
    # Jogadores
    path(r'detalhar/<int:torneio_id>/jogador/<int:jogador_id>/', views.detalhar_jogador, name='detalhar_jogador_torneio'),
    path(r'editar/<int:torneio_id>/jogador/<int:jogador_id>/', views.editar_jogador, name='editar_jogador_torneio'),
    path(r'detalhar/<int:torneio_id>/jogadores/', views.listar_jogadores, name='listar_jogadores_torneio'),
    
    # Análises
    path('analises/jogador/', views.analises_por_jogador, name='analises_torneio_por_jogador'),
    path('analises/jogador/resultado/', views.analise_resultado_torneio_para_um_jogador, name='analise_torneio_resultado_por_jogador'),
    path('analises/time/', views.analises_por_time, name='analises_torneio_por_time'),
    path('analises/time/resultado/', views.analise_resultado_torneio_para_um_time, name='analise_torneio_resultado_por_time'),
    
]

torneios/views.py
# -*- coding: utf-8 -*-
"""Views para torneios"""
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db import transaction
from django.db.models.aggregates import Count
from django.db.models.expressions import F, Case, When
from django.db.models.query_utils import Q
from django.http.response import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls.base import reverse

from jogadores.models import Jogador
from torneios.forms import CriarTorneioForm, JogadorTorneioForm, RoundForm
from torneios.models import Torneio, Partida, JogadorTorneio, Round, Time
from torneios.utils import buscar_torneio_challonge, gerar_torneio_challonge, \
    buscar_jogadores_challonge, gerar_jogadores_challonge, \
    buscar_partidas_challonge, gerar_partidas_challonge, logar_challonge, \
    vincular_automaticamente_jogadores_torneio_a_ladder, alterar_nome_rounds
    
import pandas as pd


@login_required
def criar_torneio(request):
    """Cria um torneio vinculado ao Challonge"""
    # Precisa ser admin para gerar um torneio
    if not request.user.jogador.admin:
        raise PermissionDenied
    
    if request.POST:
        form_criar_torneio = CriarTorneioForm(request.POST)
        
        if form_criar_torneio.is_valid():
            identificador_torneio = form_criar_torneio.cleaned_data['identificador_torneio']
            site = form_criar_torneio.cleaned_data['site']
            delimitador_time = form_criar_torneio.cleaned_data['delimitador_time']
            
            if site == Torneio.SITE_CHALLONGE_ID:
                # Criar um torneio vinculado ao Challonge
                try:
                    with transaction.atomic():
                        # Verificar se identificador é uma URL
                        if Torneio.SITE_CHALLONGE_URL in identificador_torneio:
                            identificador_torneio = identificador_torneio.split('/')[-1]
                        
                        # Logar
                        logar_challonge()
                        
                        # Buscar torneio
                        dados_torneio = buscar_torneio_challonge(identificador_torneio)
                        torneio = gerar_torneio_challonge(dados_torneio)
                        torneio.adicionado_por = request.user.jogador
                        torneio.save()
                        
                        # Buscar jogadores
                        dados_jogadores = buscar_jogadores_challonge(identificador_torneio)
                        jogadores, times = gerar_jogadores_challonge(dados_jogadores, torneio, delimitador_time)
                        for time in times:
                            time.save()
                        for jogador in jogadores:
                            if jogador.time:
                                jogador.time_id = jogador.time.id
                            jogador.save()
                        
                        # Buscar partidas
                        dados_partidas = buscar_partidas_challonge(identificador_torneio)
                        partidas, rounds, vitorias_por_ausencia = gerar_partidas_challonge(dados_partidas, torneio)
                        for round_torneio in rounds:
                            round_torneio.save()
                        alterar_nome_rounds(torneio)
                        for partida in partidas:
                            partida.round_id = partida.round.id
                            partida.save()
                        for vitoria_por_ausencia in vitorias_por_ausencia:
                            vitoria_por_ausencia.partida_id = vitoria_por_ausencia.partida.id
                            vitoria_por_ausencia.save()
                        
                        vincular_automaticamente_jogadores_torneio_a_ladder(torneio)
                        
                        messages.success(request, Torneio.MENSAGEM_SUCESSO_CRIACAO_TORNEIO)
                        
                        return redirect(reverse('torneios:editar_torneio', kwargs={'torneio_id': torneio.id}))
                        
                except Exception as e:
                    messages.error(request, str(e))
            else:
                raise ValueError(Torneio.MENSAGEM_ERRO_SITE_INVALIDO)
            
        else:
            for erro in form_criar_torneio.non_field_errors():
                messages.error(request, erro)
    
    else:
        form_criar_torneio = CriarTorneioForm()
    
    return render(request, 'torneios/criar_torneio.html', {'opcoes_site': Torneio.OPCOES_SITE, 'form_criar_torneio': form_criar_torneio})
    
def detalhar_torneio(request, torneio_id):
    """Detalha um torneio"""
    torneio = get_object_or_404(Torneio.objects.select_related('adicionado_por'), id=torneio_id)
    
    torneio.top_3 = JogadorTorneio.objects.filter(torneio=torneio, posicao_final__lte=3).order_by('posicao_final').select_related('time')
    
    torneio.partidas = Partida.objects.filter(round__torneio=torneio).order_by('round') \
        .select_related('jogador_1__time', 'jogador_2__time', 'round', 'ganhador')[:5]
    
    torneio.qtd_jogadores = JogadorTorneio.objects.filter(torneio=torneio, valido=True).count()
    
    return render(request, 'torneios/detalhar_torneio.html', {'torneio': torneio})

@login_required
def editar_torneio(request, torneio_id):
    """Edita um torneio"""
    # Precisa ser admin para gerar um torneio
    if not request.user.jogador.admin:
        raise PermissionDenied
    
    if request.is_ajax():
        # Verificar se foi alterado um jogador
        if request.POST.get('form-jogador'):
            instance = JogadorTorneio.objects.get(id=request.POST.get('form-jogador'))
            form_jogador = JogadorTorneioForm(request.POST, instance=instance,
                                              prefix=f'{instance.id}')
            if form_jogador.is_valid():
                jogador = form_jogador.save(commit=False)
                
                jogador.save()
                
                return JsonResponse({'mensagem': 'Jogador alterado com sucesso'})
            else:
                return JsonResponse({'mensagem': form_jogador.non_field_errors(), 'erro': True})
            
        # Verificar se a alteração foi em um round
        elif request.POST.get('form-round'):
            instance = Round.objects.get(id=request.POST.get('form-round'))
            form_round = RoundForm(request.POST, instance=instance, prefix=f'{instance.id}')
            if form_round.is_valid():
                round_torneio = form_round.save(commit=False)
                
                round_torneio.save()
                
                return JsonResponse({'mensagem': 'Round alterado com sucesso'})
            else:
                return JsonResponse({'mensagem': form_round.non_field_errors(), 'erro': True})
    else:
        torneio = get_object_or_404(Torneio, id=torneio_id)
        
        forms_jogador = list()
        for jogador in JogadorTorneio.objects.filter(torneio=torneio).order_by('seed'):
            forms_jogador.append(JogadorTorneioForm(instance=jogador, prefix=f'{jogador.id}'))
        
        # Adicionar rounds ordenando por número absoluto 
        forms_round = list()
        rounds = list()
        for round_torneio in Round.objects.filter(torneio=torneio):
            rounds.append(round_torneio)
            
        for round_torneio in sorted(rounds, key=lambda x: abs(x.indice)):
            forms_round.append(RoundForm(instance=round_torneio))
        
    return render(request, 'torneios/editar_torneio.html', {'torneio': torneio, 'forms_jogador': forms_jogador, 'forms_round': forms_round})

def listar_torneios(request):
    """Lista torneios cadastrados"""
    torneios = Torneio.objects.all().order_by('data')
    
    return render(request, 'torneios/listar_torneios.html', {'torneios': torneios})

def detalhar_partida(request, torneio_id, partida_id):
    """Detalha uma partida"""
    partida = get_object_or_404(Partida.objects.select_related('jogador_1', 'jogador_2', 'round__torneio') \
                                .select_related('jogador_1__time', 'jogador_2__time', 'ganhador__time'), id=partida_id)
    
    
    return render(request, 'torneios/detalhar_partida.html', {'partida': partida})

def listar_partidas(request, torneio_id):
    """Lista partidas cadastrados"""
    torneio = get_object_or_404(Torneio, id=torneio_id)
    partidas = Partida.objects.filter(round__torneio__id=torneio_id) \
        .select_related('jogador_1__time', 'jogador_2__time', 'ganhador__time', 'round')
    
    return render(request, 'torneios/listar_partidas.html', {'torneio': torneio, 'partidas': partidas})

def detalhar_jogador(request, torneio_id, jogador_id):
    """Detalha um jogador de um torneio"""
    jogador = get_object_or_404(JogadorTorneio.objects.select_related('jogador__user', 'torneio'), id=jogador_id)
    partidas = Partida.objects.filter(Q(jogador_1=jogador) | Q(jogador_2=jogador), round__torneio__id=jogador.torneio_id) \
        .select_related('jogador_1__time', 'jogador_2__time', 'round', 'ganhador__time')
    jogador.qtd_partidas = len(partidas)
    
    # Verificar se jogador possui outros torneios
    if jogador.jogador:
        # Precisa estar vinculado a um jogador da ladder
        jogador.outros_torneios = JogadorTorneio.objects.filter(jogador=jogador.jogador).exclude(torneio__id=torneio_id) \
            .select_related('torneio')
    
    return render(request, 'torneios/detalhar_jogador.html', {'jogador': jogador, 'partidas': partidas})

@login_required
def editar_jogador(request, torneio_id, jogador_id):
    """Detalha um jogador de um torneio"""
    if not request.user.jogador.admin:
        raise PermissionDenied
    
    jogador = get_object_or_404(JogadorTorneio, id=jogador_id)
    
    if request.POST:

templates/torneios/criar_torneio.html
{% extends 'base.html' %}
{% load static %}

{% block title %}- Criar torneio{% endblock %}

{% block page_header %}
Criar torneio
{% endblock %}

{% block extra_header %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block content %}
	<form class="col-12" action="{% url 'torneios:criar_torneio' %}" method="post">
	    {% csrf_token %}
    	{% include "form.html" with form=form_criar_torneio %}
    	
	  	<input class="btn btn-lg btn-dark mt-4" type="submit" value="Salvar">
	</form>
{% endblock %}

{% block extra_scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<script type="text/javascript">
$(document).ready(function(){
	$('select').select2();
});
</script>
{% endblock %}

templates/torneios/detalhar_jogador.html
{% extends 'base.html' %}

{% block title %}
	- {{ jogador.nome }}
{% endblock %}

{% block page_header %}
	{{ jogador.nome }}
{% endblock %}

{% block content %}
	<div class="col-12 col-md-4 my-2">
		<div class="card">
		  	<div class="card-header bg-cinza-2">
		    	Dados
		  	</div>
		  	<div class="card-body col-12">
		  		<div class="row">
			  		<div class="col-6">
					    <h6 class="card-title">Nome</h6>
					    <h6 class="card-title"><strong>{{ jogador }}</strong></h6>
				    </div>
			  		<div class="col-6">
					    <h6 class="card-title">Resultado</h6>
					    <h6 class="card-title"><strong>{{ jogador.posicao_final }}</strong></h6>
				    </div>
				    
			  		<div class="col-6">
					    <h6 class="card-title">Qtd. partidas</h6>
					    <h6 class="card-title"><strong>{{ jogador.qtd_partidas }}</strong></h6>
				    </div>
				    <div class="col-6">
					    <h6 class="card-title">Torneio</h6>
					    <h6 class="card-title"><a href="{% url 'torneios:detalhar_torneio' jogador.torneio_id %}">
						    <strong>{{ jogador.torneio.nome }}</strong>
					    </a></h6>
				    </div>
				    
				    <div class="col-6">
					    <h6 class="card-title">Vínculo na Ladder</h6>
					    <h6 class="card-title">
					    	{% if jogador.jogador %}
					    	<a href="{% url 'jogadores:detalhar_jogador' jogador.jogador.user.username %}">
					    		<strong>{{ jogador.jogador.nick }}</strong>
				    		</a>
				    		{% else %}
				    		<strong>Indefinido</strong>
				    		{% endif %}
				    	</h6>
				    </div>
			    </div>
			    
			    {% if request.user.jogador.admin %}
				<a class="card-link" href="{% url 'torneios:editar_jogador_torneio' jogador.torneio_id jogador.id %}">Editar</a>
				{% endif %}
		  	</div>
		</div>
	</div>
	
	<div class="col-12 col-md-4 my-2">
		<div class="card">
		  	<div class="card-header bg-cinza-2">
		    	Partidas
		  	</div>
		  	<div class="card-body col-12">
		  		<div class="row">
		  			{% for partida in partidas %}
		  			<div class="card col-12">
			  			<div class="card-body">
					  		<div class="row d-flex">
						  		<div class="col-5 text-left d-flex flex-column">
							    	<h5 class="card-title mb-0">{{ partida.jogador_1 }}</h5>
							    	<h6 class="card-title {% if partida.jogador_1 == partida.ganhador %}
						  				text-success
						  			{% else %}
						  				text-danger
						  			{% endif %}">{{ partida.score_1 }}</h6>
						    	</div>
						  		<div class="col-2 text-center">
							    	<h5 class="card-title">VS</h5>
						    	</div>
						  		<div class="col-5 text-right">
							    	<h5 class="card-title mb-0">{{ partida.jogador_2 }}</h5>
							    	<h6 class="card-title {% if partida.jogador_2 == partida.ganhador %}
						  				text-success
						  			{% else %}
						  				text-danger
						  			{% endif %}">{{ partida.score_2 }}</h6>
						    	</div>
					    	</div>
					    	
						    <h6 class="card-subtitle mb-2 text-muted">{{ partida.round.nome }}</h6>
						    
						    <a class="card-link" href="{% url 'torneios:detalhar_partida' jogador.torneio_id partida.id %}">Ver detalhes</a>
					  	</div>
				  	</div>
				  	{% endfor %}
				</div>
		  	</div>
		</div>
	</div>
	
	{% if jogador.outros_torneios %}
	<div class="col-12 col-md-4 my-2">
		<div class="card">
		  	<div class="card-header bg-cinza-2">
		    	Outros torneios
		  	</div>
		  	<div class="card-body col-12">
		  		<div class="row">
		  			{% for jogador_torneio in jogador.outros_torneios %}
		  			<div class="card col-12">
			  			<div class="card-body">
					    	<h5 class="card-title">{{ jogador_torneio.torneio.nome }}</h5>
					    	
						    <h6 class="card-subtitle mb-2 text-muted">{{ jogador_torneio.torneio.data }}</h6>
						    
						    <p class="card-text">{{ jogador_torneio.posicao_final }}º lugar</p>
						    
						    <a class="card-link" href="{% url 'torneios:detalhar_torneio' jogador_torneio.torneio_id %}">Ver detalhes</a>
					  	</div>
				  	</div>
				  	{% endfor %}
				</div>
		  	</div>
		</div>
	</div>
	{% endif %}
{% endblock %}

templates/torneios/detalhar_torneio.html
{% extends 'base.html' %}

{% block title %}
	- {{ torneio.nome }}
{% endblock %}

{% block page_header %}
	{{ torneio.nome }}
{% endblock %}

{% block content %}
	<div class="col-12 col-md-4 my-2">
		<div class="card">
		  	<div class="card-header bg-cinza-2">
		    	Dados
		  	</div>
		  	<div class="card-body col-12">
		  		<div class="row">
			  		<div class="col-6">
					    <h6 class="card-title">Nome</h6>
					    <h6 class="card-title"><strong>{{ torneio.nome }}</strong>
					    </h6>
				    </div>
			  		<div class="col-6">
					    <h6 class="card-title">Data</h6>
					    <h6 class="card-title"><strong>{{ torneio.data|date:'d/m/Y' }}</strong></h6>
				    </div>
			    
			  		<div class="col-6">
					    <h6 class="card-title">Qtd. jogadores</h6>
					    <h6 class="card-title"><strong>{{ torneio.qtd_jogadores }}</strong></h6>
				    </div>
				    <div class="col-6">
					    <h6 class="card-title">Adicionado por</h6>
					    <h6 class="card-title"><strong>{{ torneio.adicionado_por }}</strong></h6>
				    </div>
				    
				    <div class="col-12">
					    <h6 class="card-title">URL</h6>
					    <h6 class="card-title"><a href="{{ torneio.url }}">{{ torneio.url }}</a></h6>
				    </div>
			    </div>
				
				{% if request.user.jogador.admin %}
				<a class="card-link" href="{% url 'torneios:editar_torneio' torneio.id %}">Editar</a>
				{% endif %}
		  	</div>
		</div>
	</div>
	
	<div class="col-12 col-md-4 my-2">
		<div class="card">
		  	<div class="card-header bg-cinza-2">
		    	Jogadores
		  	</div>
		  	<ul class="list-group list-group-flush">
			  	{% for jogador in torneio.top_3 %}
					<li class="list-group-item">
						<span>{{ forloop.counter }}: <a href="{% url 'torneios:detalhar_jogador_torneio' torneio.id jogador.id %}">{{ jogador }}</a></span>
					</li>
				{% endfor %}
		  	</ul>
		  	<div class="card-body col-12 text-center">
				<a class="card-link" href="{% url 'torneios:listar_jogadores_torneio' torneio.id %}">Ver todos</a>
		  	</div>
		</div>
	</div>
	
	<div class="col-12 col-md-4 my-2">
		<div class="card">
		  	<div class="card-header bg-cinza-2">
		    	Partidas
		  	</div>
		  	<div class="card-body col-12">
		  		<div class="row">
		  			{% for partida in torneio.partidas %}
		  			<div class="card col-12">
			  			<div class="card-body">
					  		<div class="row d-flex">
						  		<div class="col-5 text-left d-flex flex-column">
							    	<h5 class="card-title mb-0">{{ partida.jogador_1 }}</h5>
							    	<h6 class="card-title {% if partida.jogador_1 == partida.ganhador %}
						  				text-success
						  			{% else %}
						  				text-danger
						  			{% endif %}">{{ partida.score_1 }}</h6>
						    	</div>
						  		<div class="col-2 text-center">
							    	<h5 class="card-title">VS</h5>
						    	</div>
						  		<div class="col-5 text-right">
							    	<h5 class="card-title mb-0">{{ partida.jogador_2 }}</h5>
							    	<h6 class="card-title {% if partida.jogador_2 == partida.ganhador %}
						  				text-success
						  			{% else %}
						  				text-danger
						  			{% endif %}">{{ partida.score_2 }}</h6>
						    	</div>
					    	</div>
					    	
						    <h6 class="card-subtitle mb-2 text-muted">{{ partida.round.nome }}</h6>
						    
						    <a class="card-link" href="{% url 'torneios:detalhar_partida' torneio.id partida.id %}">Ver detalhes</a>
					  	</div>
				  	</div>
				  	{% endfor %}
		  			
					<div class="col-12 text-center mt-3 mb-0">
						<a class="card-link" href="{% url 'torneios:listar_partidas' torneio.id %}">Ver todas</a>
					</div>
				</div>
		  	</div>
		</div>
	</div>
{% endblock %}

templates/torneios/editar_jogador.html
{% extends 'base.html' %}
{% load static %}

{% block title %}- Editar {{ jogador.nome }}{% endblock %}

{% block page_header %}
Editar {{ jogador.nome }}
{% endblock %}

{% block extra_header %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block content %}
	<form class="col-12" action="{% url 'torneios:editar_jogador_torneio' form_jogador.instance.torneio_id form_jogador.instance.id %}" method="post">
	    {% csrf_token %}
    	{% include "form.html" with form=form_jogador %}
    	
	  	<input class="btn btn-lg btn-dark mt-4" type="submit" value="Salvar">
	</form>
{% endblock %}

{% block extra_scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script src={% static "jquery.mask.min.js" %} type="text/javascript"></script>

<script type="text/javascript">
$(document).ready(function(){
	$('select').select2();
});
</script>
{% endblock %}