jogadores/urls.py
from django.urls import path
from jogadores import views

app_name='jogadores'
urlpatterns = [
    path(r'listar/', views.listar_jogadores, name='listar_jogadores'),
    path(r'detalhar/<slug:username>/', views.detalhar_jogador, name='detalhar_jogador'),
    path(r'editar/<slug:username>/', views.editar_jogador, name='editar_jogador'),
]

ladder/urls.py
from django.urls import path

from ladder import views

app_name='ladder'
urlpatterns = [
    # Ladder
    path(r'atual/', views.detalhar_ladder_atual, name='detalhar_ladder_atual'),
    path(r'hall-fama/<int:ano>/<int:indice>/', views.detalhar_hall_fama, name='detalhar_hall_fama'),
    path(r'historico/<int:ano>/<int:mes>/', views.detalhar_ladder_historico, name='detalhar_ladder_historico'),
    path(r'hall-fama/listar/', views.listar_hall_fama, name='listar_hall_fama'),
    path(r'historico/listar/', views.listar_ladder_historico, name='listar_ladder_historico'),
    path(r'atual/listar-desafios/', views.listar_desafios_ladder, name='listar_desafios_ladder_atual'),
    path(r'historico/<int:ano>/<int:mes>/listar-desafios/', views.listar_desafios_ladder, name='listar_desafios_ladder_historico'),
    path(r'hall-fama/<int:ano>/<int:indice>/listar-desafios/', views.listar_desafios_season, name='listar_desafios_season'),
    
    # Remoções
    path(r'cancelar-remocao/<int:remocao_id>/', views.cancelar_remocao_jogador_ladder, name='cancelar_remocao_jogador_ladder'),
    path(r'listar-remocoes/', views.listar_remocoes_jogador_ladder, name='listar_remocoes_jogador_ladder'),
    path(r'remover-jogador/', views.remover_jogador_ladder, name='remover_jogador_ladder'),
    
    # Permissões de aumento de range
    path(r'permissao-aumento-range/adicionar/', views.add_permissao_aumento_range, name='add_permissao_aumento_range'),
    path(r'permissao-aumento-range/remover/', views.remover_permissao_aumento_range, name='remover_permissao_aumento_range'),
    path(r'permissao-aumento-range/remover/<int:permissao_id>/', views.remover_permissao_aumento_range, name='remover_permissao_aumento_range'),
    
    # Desafios de ladder
    path(r'desafio/adicionar/', views.add_desafio_ladder, name='adicionar_desafio_ladder'),
    path(r'desafio/cancelar/<int:desafio_id>/', views.cancelar_desafio_ladder, name='cancelar_desafio_ladder'),
    path(r'desafio/detalhar/<int:desafio_id>/', views.detalhar_desafio_ladder, name='detalhar_desafio_ladder'),
    path(r'desafio/editar/<int:desafio_id>/', views.editar_desafio_ladder, name='editar_desafio_ladder'),
    path(r'desafio/listar-pendentes/', views.listar_desafios_ladder_pendentes_validacao, name='listar_desafios_ladder_pendentes_validacao'),
    path(r'desafio/validar/<int:desafio_id>/', views.validar_desafio_ladder, name='validar_desafio_ladder'),
    
    # Regras
    path(r'regras/', views.detalhar_regras, name='detalhar_regras_ladder'),
    
    # Lutas
    path(r'lutas/detalhar/<int:luta_id>/', views.detalhar_luta, name='detalhar_luta'),
    
    # Análises
    path('analises/geral/', views.analises, name='analises'),
    path('analises/geral/resultado-acumulado-jogadores/', views.analise_resultado_acumulado_jogadores, name='analise_result_acum_jogadores'),
    path('analises/geral/resultado-posicao/', views.analise_resultado_por_posicao, name='analise_resultado_por_posicao'),
    path('analises/geral/resultado-diferenca-posicao/', views.analise_resultado_por_diferenca_posicao, name='analise_resultado_por_diferenca_posicao'),
    path('analises/geral/vitorias-por-personagem/', views.analise_vitorias_por_personagem, name='analise_vitorias_por_personagem'),
    path('analises/jogador/', views.analises_por_jogador, name='analises_por_jogador'),
    path('analises/jogador/resultado-acumulado-jogador/', views.analise_resultado_acumulado_para_um_jogador, name='analise_result_acum_jogador'),
    path('analises/jogador/resultado-contra-personagens-jogador/', views.analise_resultado_acumulado_contra_personagens_para_um_jogador, 
         name='analise_result_jogador_contra_personagens'),
    path('analises/jogador/resultado-stages-jogador/', views.analise_resultado_stages_para_um_jogador, name='analise_stages_jogador'),
    path('analises/jogador/vitorias-desafio/', views.analise_vitorias_desafio_para_um_jogador, name='analise_vitorias_desafio_jogador'),
]

smashLadder/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls.conf import re_path
from django.views.defaults import page_not_found

from ladder.models import Lockdown
from smashLadder import views, settings


urlpatterns = []

# Verificar lockdown de seasons
try:
    if Lockdown.sistema_em_lockdown():
        urlpatterns.append(re_path(r'.*?', page_not_found, {'exception': Exception('Gerando nova Season')}))
except:
    pass
        
urlpatterns.extend([
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', views.home, name='inicio'),
    
    path('jogadores/', include('jogadores.urls.urls_jogadores')),
    path('ladder/', include('ladder.urls')),
    path('personagens/', include('jogadores.urls.urls_personagens')),
    path('stages/', include('jogadores.urls.urls_stages')),
    path('torneios/', include('torneios.urls')),
    path('treinamento/', include('treinamento.urls')),
])

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

torneios/urls.py
"""
Configuração de URL para torneios
"""
from django.urls import path
from torneios import views

app_name='torneios'
urlpatterns = [
    # Torneios
    path(r'criar/', views.criar_torneio, name='criar_torneio'),
    path(r'detalhar/<int:torneio_id>/', views.detalhar_torneio, name='detalhar_torneio'),
    path(r'editar/<int:torneio_id>/', views.editar_torneio, name='editar_torneio'),
    path(r'listar/', views.listar_torneios, name='listar_torneios'),
    
    # Partidas
    path(r'detalhar/<int:torneio_id>/partida/<int:partida_id>/', views.detalhar_partida, name='detalhar_partida'),
    path(r'detalhar/<int:torneio_id>/partidas/', views.listar_partidas, name='listar_partidas'),
    
    # Jogadores
    path(r'detalhar/<int:torneio_id>/jogador/<int:jogador_id>/', views.detalhar_jogador, name='detalhar_jogador_torneio'),
    path(r'editar/<int:torneio_id>/jogador/<int:jogador_id>/', views.editar_jogador, name='editar_jogador_torneio'),
    path(r'detalhar/<int:torneio_id>/jogadores/', views.listar_jogadores, name='listar_jogadores_torneio'),
    
    # Análises
    path('analises/jogador/', views.analises_por_jogador, name='analises_torneio_por_jogador'),
    path('analises/jogador/resultado/', views.analise_resultado_torneio_para_um_jogador, name='analise_torneio_resultado_por_jogador'),
    path('analises/time/', views.analises_por_time, name='analises_torneio_por_time'),
    path('analises/time/resultado/', views.analise_resultado_torneio_para_um_time, name='analise_torneio_resultado_por_time'),
    
]

treinamento/urls.py
"""
Configuração de URL para treinamento
"""
from django.urls import path

from treinamento import views


app_name='treinamento'
urlpatterns = [
    path(r'', views.painel_treinamento, name='painel_treinamento'),
    
    # Registros de treinamento
    path(r'registro/<int:registro_id>/adicionar-resultado/', views.add_resultado_treinamento, name='add_resultado_treinamento'),
    path(r'registro/<int:registro_id>/apagar/', views.apagar_registro_treinamento, name='apagar_registro_treinamento'),
    path(r'registro/<int:registro_id>/detalhar/', views.detalhar_registro_treinamento, name='detalhar_registro_treinamento'),
    path(r'registro/<int:registro_id>/editar/', views.editar_registro_treinamento, name='editar_registro_treinamento'),
    path(r'registro/adicionar/', views.add_registro_treinamento, name='add_registro_treinamento'),
    path(r'registro/listar/', views.listar_registros_treinamento, name='listar_registros_treinamento'),
    
    # Anotações
    path(r'anotacao/adicionar/', views.add_anotacao, name='add_anotacao'),
    path(r'anotacao/<int:anotacao_id>/apagar/', views.apagar_anotacao, name='apagar_anotacao'),
    path(r'anotacao/listar/', views.listar_anotacoes, name='listar_anotacoes'),
    
    # Anotações
    path(r'link-util/adicionar/', views.add_link_util, name='add_link_util'),
    path(r'link-util/<int:link_util_id>/apagar/', views.apagar_link_util, name='apagar_link_util'),
    path(r'link-util/listar/', views.listar_links_uteis, name='listar_links_uteis'),
    
    # Métricas
    path(r'metrica/adicionar/', views.add_metrica, name='add_metrica'),
    path(r'metrica/<int:metrica_id>/apagar/', views.apagar_metrica, name='apagar_metrica'),
    path(r'metrica/<int:metrica_id>/detalhar/', views.detalhar_metrica, name='detalhar_metrica'),
    path(r'metrica/<int:metrica_id>/editar/', views.editar_metrica, name='editar_metrica'),
    path(r'metrica/listar/', views.listar_metricas, name='listar_metricas'),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
	  	<meta charset="utf-8">
	  	<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
	  	<title>{{ NOME_SITE }} {% block title %}{% endblock %}</title>
	  	
	  	{% comment %}
	  	CSS
	  	{% endcomment %}
	  	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static "custom.css" %}" type="text/css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
		{% block extra_header %}
		
		{% endblock %}
		
		{% comment %}
		Codigo para Google Analytics
		{% endcomment %}
		{% if PROD %}
	        {% include "analytics.html" %}
        {% endif%}
	</head>
	<body class="bg-cinza-1">
	  	<main class="pb-5">
			<nav class="navbar navbar-expand-lg navbar-light bg-cinza-3 site-header sticky-top">
	  			<a class="navbar-brand" href="{% url 'inicio' %}">
	  				<img src="{% static "img/misc/cdl_logo_red.png" %}" width="60" alt="Clube da Luta"/>
  				</a>
			  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			    	<span class="navbar-toggler-icon"></span>
			  	</button>
			
			  	<div class="collapse navbar-collapse" id="navbarSupportedContent">
			    	<ul class="navbar-nav mr-auto">
			      		<li class="nav-item {% if request.resolver_match.url_name == 'inicio' %}active{% endif %}">
			        		<a class="nav-link" href="{% url 'inicio' %}">Início</a>
			      		</li>
			      		
			      		<li class="nav-item dropdown {% if 'jogadores' in request.resolver_match.namespace %}active{% endif %}"">
			        		<a class="nav-link dropdown-toggle" href="#" id="jogadoresDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			          			Jogadores
			        		</a>
			        		<div class="dropdown-menu" aria-labelledby="jogadoresDropdown">
	  							<a class="dropdown-item" href="{% url 'jogadores:adicionar_sugestao' %}">Adicionar sugestão</a>
	  							<a class="dropdown-item" href="{% url 'jogadores:listar_jogadores' %}">Ver jogadores</a>
	  							<a class="dropdown-item" href="{% url 'jogadores:listar_sugestoes' %}">Ver sugestões</a>
		        			</div>
		        		</li>
		        		
		        		<li class="nav-item dropdown {% if 'personagens' in request.resolver_match.namespace %}active{% endif %}"">
			        		<a class="nav-link dropdown-toggle" href="#" id="personagensDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			          			Personagens
			        		</a>
			        		<div class="dropdown-menu" aria-labelledby="personagensDropdown">
	  							<a class="dropdown-item" href="{% url 'personagens:listar_personagens' %}">Ver personagens</a>
		        			</div>
		        		</li>
		        		
		        		<li class="nav-item dropdown {% if 'stages' in request.resolver_match.namespace %}active{% endif %}">
			        		<a class="nav-link dropdown-toggle" href="#" id="stagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			          			Stages
			        		</a>
			        		<div class="dropdown-menu" aria-labelledby="stagesDropdown">
	  							{% if request.user.jogador.admin %}
	  								<a class="dropdown-item" href="{% url 'stages:editar_stages_validas' %}">Editar stages válidas p/ Ladder</a>
  								{% endif %}
	  							<a class="dropdown-item" href="{% url 'stages:listar_stages' %}">Ver stages</a>
	  							<a class="dropdown-item" href="{% url 'stages:listar_stages_validas' %}">Ver stages válidas p/ Ladder</a>
	  							
		        			</div>
		        		</li>
		        		
		        		<li class="nav-item dropdown 
		        		{% if 'ladder' in request.resolver_match.namespace and not request.resolver_match.url_name == 'detalhar_regras_ladder' %}
		        		active
		        		{% endif %}">
			        		<a class="nav-link dropdown-toggle" href="#" id="ladderDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			          			Ladder
			        		</a>
			        		<ul class="dropdown-menu" aria-labelledby="ladderDropdown">
					  			<li><a class="dropdown-item" href="{% url 'ladder:adicionar_desafio_ladder' %}">Adicionar desafio</a></li>
					  			
					  			{% if request.user.jogador.admin %}
	  							<li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="javascript:;">Aumento de Range</a>
						            <ul class="dropdown-menu">
				              			<li><a class="dropdown-item" href="{% url 'ladder:add_permissao_aumento_range' %}">Permitir</a></li>
				              			<li><a class="dropdown-item" href="{% url 'ladder:remover_permissao_aumento_range' %}">Remover permissão</a></li>
			              			</ul>
		              			</li>
		              			{% endif %}
					  			
	  							<li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="javascript:;">Análises</a>
						            <ul class="dropdown-menu">
				              			<li><a class="dropdown-item" href="{% url 'ladder:analises' %}">Geral</a></li>
				              			<li><a class="dropdown-item" href="{% url 'ladder:analises_por_jogador' %}">Por jogador</a></li>
			              			</ul>
		              			</li>
					  			<li><a class="dropdown-item" href="{% url 'ladder:listar_hall_fama' %}">Hall da Fama</a></li>
					  			<li><a class="dropdown-item" href="{% url 'ladder:listar_ladder_historico' %}">Histórico da Season</a></li>
					  			<li><a class="dropdown-item" href="{% url 'ladder:detalhar_ladder_atual' %}">Ladder atual</a></li>
					  			
					  			<li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="javascript:;">Remoções da ladder</a>
						            <ul class="dropdown-menu">
	  									{% if request.user.jogador.admin %}
				              				<li><a class="dropdown-item" href="{% url 'ladder:listar_remocoes_jogador_ladder' %}">Cancelar remoção</a></li>
		              					{% endif %}
				              			<li><a class="dropdown-item" href="{% url 'ladder:listar_remocoes_jogador_ladder' %}">Listar remoções</a></li>
	  									{% if request.user.jogador.admin %}
				              				<li><a class="dropdown-item" href="{% url 'ladder:remover_jogador_ladder' %}">Remover jogador</a></li>
		              					{% endif %}
			              			</ul>
		              			</li>
		              			
					  			<li><a class="dropdown-item" href="{% url 'ladder:listar_desafios_ladder_pendentes_validacao' %}">Ver desafios a validar</a></li>
		        			</ul>
		        		</li>
		        		
			      		<li class="nav-item {% if request.resolver_match.url_name == 'detalhar_regras_ladder' %}active{% endif %}">
			        		<a class="nav-link" href="{% url 'ladder:detalhar_regras_ladder' %}">Regras</a>
			      		</li>
			      		
		        		<li class="nav-item dropdown {% if 'torneios' in request.resolver_match.namespace %}active{% endif %}">
			        		<a class="nav-link dropdown-toggle" href="#" id="torneiosDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			          			Torneios
			        		</a>
			        		<ul class="dropdown-menu" aria-labelledby="torneiosDropdown">
	  							{% if request.user.jogador.admin %}
	  							<li><a class="dropdown-item" href="{% url 'torneios:criar_torneio' %}">Adicionar torneio</a></li>
	  							{% endif %}
	  							
	  							<li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="javascript:;">Análises</a>
						            <ul class="dropdown-menu">
				              			<li><a class="dropdown-item" href="{% url 'torneios:analises_torneio_por_jogador' %}">Por jogador</a></li>
				              			<li><a class="dropdown-item" href="{% url 'torneios:analises_torneio_por_time' %}">Por time</a></li>
			              			</ul>
		              			</li>
	  							
	  							<li><a class="dropdown-item" href="{% url 'torneios:listar_torneios' %}">Listar torneios</a></li>
		        			</ul>
		        		</li>
			    	</ul>
			    	
				    <div class="my-2 my-lg-0">
				    	<ul class="navbar-nav">
		  				{% if request.user.is_authenticated %}
		  					<li class="nav-item dropdown" id="menu_jogador">
				        		<a class="nav-link dropdown-toggle" href="#" id="jogadorDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				          			{{ request.user.username }}
				        		</a>
				        		<div class="dropdown-menu dropdown-menu-right" aria-labelledby="jogadorDropdown">
				        			<a class="dropdown-item" href="{% url 'jogadores:listar_desafiaveis' request.user.username %}">Jogadores desafiáveis</a>
				          			<a class="dropdown-item" href="{% url 'jogadores:detalhar_jogador' request.user.username %}">Meu perfil</a>
				          			<a class="dropdown-item" href="{% url 'jogadores:listar_avaliacoes' %}">Meu feedback 
				          				<span class="badge badge-pill badge-dark" id="jogador_qtd_feedbacks"></span>
				          			</a>
				          			<a class="dropdown-item" href="{% url 'treinamento:painel_treinamento' %}">Treinamento</a>
				          			<div class="dropdown-divider"></div>
			          				<a class="dropdown-item" href="{% url 'logout' %}">Sair</a>
			        			</div>
		        			</li>
		  				{% else %}
		  					<li class="nav-item {% if request.resolver_match.url_name == 'inicio' %}active{% endif %}">
				        		<a class="nav-link" href="{% url 'login' %}?next={{request.path}}">Login</a>
				      		</li>
			  				
			  			{% endif %}
	        			</ul>
			  		</div>
			  </div>
			</nav>
			
  			<div class="container-fluid mt-2">
		  		<div class="row mx-2 mt-3">
		  			{% if messages %}
					<ul class="messages col-12">
					    {% for message in messages %}
					    <div class="alert alert-{{ message.level_tag }}" role="alert">
					  		{% if 'safe' in message.tags %}
					  			{{ message|safe }}
					  		{% else %}
					  			{{ message }}
				  			{% endif %}
						</div>
					    {% endfor %}
					</ul>
					{% endif %}
		  		</div>
	  		
				<div class="row mx-2 my-3">
				
					<div class="col-12 text-center mb-3">
						<h1>
						{% block page_header %}
						
						{% endblock %}
						</h1>
					</div>
					
			    	{% block content %}
			    	
			    	{% endblock %}
		    	</div>
	    	</div>
	  	</main>
	  	<footer class="footer bg-cinza-2 fixed-bottom">
	      	<div class="d-flex justify-content-around pt-2">
	        	<a href="https://discordapp.com/channels/463864267402379265/470807119713533964">
	        		<i class="fab fa-discord fa-2x"></i>
	        	</a>
	        	<a href="https://www.facebook.com/CDLDF">
	        		<i class="fab fa-facebook fa-2x"></i>
	        	</a>
	        	<a href="https://www.instagram.com/cdl_df">
	        		<i class="fab fa-instagram fa-2x"></i>
	        	</a>
	        	<a href="https://twitter.com/ClubeDaLutaDF">
	        		<i class="fab fa-twitter fa-2x"></i>
	        	</a>
	      	</div>
	    </footer>
	  	
	    	
    	<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    	<script type="text/javascript">
			var token = '{{csrf_token}}';
			
    		$('.dropdown-menu a.dropdown-toggle').on('click', function(e) {
			  if (!$(this).next().hasClass('show')) {
			    $(this).parents('.dropdown-menu').first().find('.show').removeClass("show");
			  }
			  var $subMenu = $(this).next(".dropdown-menu");
			  $subMenu.toggleClass('show');
			
			
			  $(this).parents('li.nav-item.dropdown.show').on('hidden.bs.dropdown', function(e) {
			    $('.dropdown-submenu .show').removeClass("show");
			  });
			
			
			  return false;
			});
			function ajax(url, method, data, successFunction) {
				$.ajax({
			        url : url,
			        type : method,
			        data : data,
			        dataType: 'json',
			        headers: { "X-CSRFToken": token },
			
			        // handle a successful response
			        success : function(resultado) {
			        	successFunction(resultado);
			        },
			
			        // handle a non-successful response
			        error : function(xhr,errmsg,err) {
			            console.log(xhr.status + ": " + xhr.responseText);
			        }
			    });
			}    	
			
			$(document).ready(function(){
				$('#menu_jogador').click(function() {
					ajax("{% url 'jogadores:buscar_qtd_feedbacks' %}", 
						'GET', 
						{}, 
						function(resultado) {
				        	// Verifica mensagem de erro
				        	if (resultado.mensagem_erro) {
				        		return;
				        	} 
				        	else {
				        		if (resultado.qtd_feedbacks > 0) {
				        			$('#jogador_qtd_feedbacks').html(resultado.qtd_feedbacks);
				        		}
				        	}
				        }
				    );
			    });
		    });
    	</script>
    	{% block extra_scripts %}
    	
    	{% endblock %}
	</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}- Home{% endblock %}

{% block page_header %}Bem-vindo à {{ JOGO }} Ladder {{ UF }}!{% endblock %}

{% block content %}
	<div class="col-12 d-flex justify-content-center">
		<h5>Top 10</h5>
	</div>
	<div class="col-12 d-md-flex justify-content-md-center">
		<ul class="list-group col-md-3 ladder-top-10 pr-0">
		{% for posicao_ladder in top_10_ladder %}
			<li class="list-group-item d-flex align-items-center">
				<div class="col-2 pl-0 posicao-ladder"><strong>{{ posicao_ladder.posicao }}</strong></div>
				<a class="col-6 text-center" href="{% url 'jogadores:detalhar_jogador' posicao_ladder.jogador.user.username %}">{{ posicao_ladder.jogador.nick }}</a>
				{% if posicao_ladder.posicao == 1 and posicao_ladder.jogador.main %}
					<img title="{{ posicao_ladder.jogador.main.nome }}" class="ml-auto ladder-personagem" src="{% static posicao_ladder.jogador.main.imagem %}" />
				{% elif posicao_ladder.jogador.main %}
					<div class="col-4 text-center">
						<img title="{{posicao_ladder.jogador.main.nome }}" class="icone-personagem text-center" src="{% static posicao_ladder.jogador.main.icone %}" />
					</div>
				{% endif %}
			</li>
		{% endfor %}
		</ul>
	</div>
	
	<div class="mt-4 col-12 d-flex justify-content-center">
		<h5>Últimos desafios adicionados</h5>
	</div>
	{% for desafio_ladder in ultimos_desafios_ladder %}
	<div class="card col-12 col-md-3">
	  	<div class="card-body">
	  		<div class="row d-flex">
		  		<div class="col-5 text-left d-flex flex-column">
			    	<h5 class="card-title mb-0">{{ desafio_ladder.desafiante.nick }}</h5>
			    	<h6 class="card-title {% if desafio_ladder.score_desafiante > desafio_ladder.score_desafiado %}
		  				text-success
		  			{% else %}
		  				text-danger
		  			{% endif %}">{{desafio_ladder.score_desafiante}}</h6>
		    	</div>
		  		<div class="col-2 text-center">
			    	<h5 class="card-title">VS</h5>
		    	</div>
		  		<div class="col-5 text-right">
			    	<h5 class="card-title mb-0">{{ desafio_ladder.desafiado.nick }}</h5>
			    	<h6 class="card-title
		  			{% if desafio_ladder.score_desafiado > desafio_ladder.score_desafiante %}
		  				text-success
		  			{% else %}
		  				text-danger
		  			{% endif %}">{{desafio_ladder.score_desafiado}}</h6>
		    	</div>
	    	</div>
	    	
		    <h6 class="card-subtitle mb-2 text-muted">{{ desafio_ladder.data_hora|date:'d/m/Y H:i' }}</h6>
		    
		    {% if desafio_ladder.is_cancelado %}
		    	<p class="card-text">Desafio cancelado</p>
		    {% elif desafio_ladder.is_validado %}
		    	<p class="card-text">Desafio validado</p>
		    {% else %}
		    	<p class="card-text">Desafio aguardando validação</p>
		    {% endif %}
		    
		    <a class="card-link" href="{% url 'ladder:detalhar_desafio_ladder' desafio_ladder.id %}">Ver detalhes</a>
	    	{% if request.user.jogador.admin and not desafio_ladder.is_validado %}
		    	<a class="card-link" href="{% url 'ladder:validar_desafio_ladder' desafio_ladder.id %}">Validar</a>
		    {% endif %}
			{% if desafio_ladder.is_cancelavel %}			    
		    	<a class="card-link" href="{% url 'ladder:cancelar_desafio_ladder' desafio_ladder.id %}">Cancelar</a>
	    	{% endif %}
	  	</div>
	</div>
	{% endfor %}
{% endblock %}